# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run tests
        run: cd githubpagesdemo && ./gradlew test

      # Runs a set of commands using the runners shell
      - name: Build Jar
        run: cd githubpagesdemo && ./gradlew build -x test
        
      - name: Run jar and query
        run: |
          cd githubpagesdemo && java -Djava.net.preferIPv4Stack=true -jar build/libs/githubpagesdemo-0.0.1-SNAPSHOT.jar &
          echo $(curl 127.0.0.1:8080/api/)
        
        

